== Confluence Publisher
Конвертация документов в формате Asciidoc в формат хранения Confluence и публикация на сервер Confluence.

== Функциональность

Программа имеет интерфейс CLI. Предназначена для конвертации одного документа в формате Asciidoc в формат хранения Confluence и публикации на сервер Confluence. При этом выполняется также загрузка изображений, используемых в статье.

Заголовок документа (заголовок первого уровня) используется в качестве названия статьи. Он же используется для поиска статьи в пространстве Confluence, если явно не указан идентификатор статьи.


=== Особенности загрузки изображений

Изображения загружаются во вложения Confluence под теми именами, которые имеют их файлы. Поэтому, в одной статье не должно быть изображений, файлы которых имеют одинаковое имя.

Если при загрузке файла изображения во вложениях статьи уже имеется файл с таким же именем, будет выполнено обновление. Перед обновлением сверяются sha1-хэши файлов, и обновление выполняется только в том случае, если они различаются. Если установлено, что файл всё же изменился, он загружается во вложения Confluence под тем же именем, При этом возникает новая версия данного вложения и она становится текущей. Во всех версиях самой статьи, где используется это изображение, будет отображаться именно текущая версия.

Удаления вложений, которые более не упоминаются в статье, система не выполняет, но выводит информационное сообщение о наличии таких вложений. При этом учитывается только текущая публикуемая версия статьи. Если вложение упоминается в предыдущих версиях статьи, а в текущей его нет, оно будет обозначено как неиспользуемое.

При загрузке вложений сверки по их контенту не происходит. Поэтому, при переименовании файла изображения произойдёт загрузка нового вложения, а вложение под старым именем останется, но может стать неиспользуемым.