:toc: left
:toc-title: Оглавление
:icons: font

== Confluence Publisher
Конвертация документов в формате Asciidoc в формат хранения Confluence и публикация на сервер Confluence.

== Функциональность

Программа имеет интерфейс CLI. Предназначена для конвертации одного документа в формате Asciidoc в формат хранения Confluence и публикации на сервер Confluence. При этом выполняется также загрузка изображений, используемых в статье.

Заголовок документа (заголовок первого уровня) используется в качестве названия страницы. Он же используется для поиска страницы в пространстве Confluence, если явно не указан её идентификатор.

Предусмотрено два режима публикации страницы: первичная публикация и обновление.

=== Первичная публикация страницы

Первичная публикация предполагает, что на момент её выполнения в указанном пространстве не будет страницы с таким же названием, как у публикуемой. При публикации выполняется проверка, и, если она обнаружит, что страница с таким названием уже имеется, произойдёт отказ в публикации. Это позволяет предохранить от затирания другую страницу, с которой совпало название публикуемой.

Для первичной публикации обязательно нужно указать ключ пространства, в которое будет выполнена публикация, а также идентификатор родительской страницы.

=== Обновление опубликованной ранее страницы

При обновлении опубликованной ранее страницы происходит замещение контента существующей на Confluence страницы. При этом, в отличие от первичной публикации, отказ произойдёт, если не удастся найти в Confluence существующую страницу для обновления.

Страница для обновления ищется всегда по идентификатору в Confluence. Если утилита вызвана для обновления одной страницы, необходимо указать идентификатор в параметре вызова `page-id`. В режиме пакетного обновления идентификаторы должны присутствовать в файле со списком страниц. Файл задаётся в параметре `list-file`. В режиме обновления указывать пространство и родительскую страницу не нужно.

=== Особенности загрузки изображений

Изображения загружаются во вложения Confluence под теми именами, которые имеют их файлы. Поэтому, в одной странице не должно быть изображений, файлы которых имеют одинаковое имя.

Если при загрузке файла изображения во вложениях страницы уже имеется файл с таким же именем, будет выполнено обновление. Перед обновлением сверяются sha1-хэши файлов, и обновление выполняется только в том случае, если они различаются. Если установлено, что файл всё же изменился, он загружается во вложения Confluence под тем же именем, При этом возникает новая версия данного вложения и она становится текущей. Во всех версиях самой страницы, где используется это изображение, будет отображаться именно текущая версия.

Удаления вложений, которые более не упоминаются в странице, система не выполняет, но выводит информационное сообщение о наличии таких вложений. При этом учитывается только текущая публикуемая версия страницы. Если вложение упоминается в предыдущих версиях страницы, а в текущей его нет, оно будет обозначено как неиспользуемое.

При загрузке вложений сверки по их контенту не происходит. Поэтому, при переименовании файла изображения произойдёт загрузка нового вложения, а вложение под старым именем останется, но может стать неиспользуемым.


== Конвертация

=== Особенности конвертации ссылок на якоря

Неожиданно оказалось, что при формировании ссылки на якорь Confluence добавляет префикс `[inlineExtension]` перед идентификатором якоря. В итоге _фрагмент_ URL может выглядеть так:

[.text-center]
`#%5BinlineExtension%5DlinkConversion`

Соответственно, при конвертации ссылки, если эта ссылка локальная, нужно добавлять этот префикс. Локальную ссылку определить просто — её `target` будет начинаться с символа `#`.

В некоторых случаях может получаться работающая ссылка, даже если не добавить префикс. Это происходит в случае, когда идентификатор ссылки на заголовок совпадает с идентификатором заголовка, который автоматически создаёт Confluence. Но добавление префикса всё же является более универсальным решением, так как оно работает всегда.

[IMPORTANT]
При использовании локальных ссылок на заголовки рекомендуется всегда явно задавать якорь для таких заголовков.


=== Преобразование ссылок на тикеты Jira в макросы

Публикатор умеет преобразовывать ссылки на тикеты Jira в макросы. Это когда вместо ссылки выводится плашка с кодом и описанием тикета, а также с указанием его статуса. Чтобы такое преобразование происходило нужно, чтобы для документа были указаны три атрибута:

[cols="1,3"]
|===

|jira-url
|Базовая часть URL к Jira. По ней конвертер будет распознавать ссылки на тикеты. К базовой части в данном случае относится весь URL кроме кода задачи.

|jira-server
|Название сервера Jira, как оно зарегистрировано в интеграции с Confluence.

|jira-server-id
|Идентификатор сервера Jira.
|===

В формате хранения макрос выглядит так:
[source%nowrap, xhtml]
----
<ac:structured-macro ac:name="jira" ac:schema-version="1"
                     ac:macro-id="635371f3-2225-412f-9fdd-2aae9dcb6e87">
    <ac:parameter ac:name="server">System Jira</ac:parameter>
    <ac:parameter ac:name="serverId">d19e62e1-c77e-4c55-a315-6b41686fa467</ac:parameter>
    <ac:parameter ac:name="key">DUD-5037</ac:parameter>
</ac:structured-macro>
----

А исходная ссылка для такого макроса могла быть такой:

[.text-center]
`https://mana.atlassian.net/browse/DUD-5037` +
(jira-url = `https://mana.atlassian.net/browse/`)


=== Особенности конвертации таблиц

Иногда нужно получить в Confluence более широкую таблицу, чтобы объёмное содержимое более удачно помещалось в ячейках и не возникало лишних переносов в строках. Для этого к таблице нужно указать специальный атрибут `wide`. Вместе с тем можно использовать и другие стандартные атрибуты, предусмотренные в Asciidoctor, например, `cols` для указания относительных ширин колонок.

[source%nowrap, asciidoctor]
----
[wide="true", cols="4,6"]
|===
|Ячейка 1 |Ячейка 2
|===
----

=== Примечания (Admonitions)

Примечания (Admonitions) используются для смыслового выделения фрагментов текста. Набор доступных примечаний в _Asciidoctor_ не идентичен вариантам, имеющимся в _Confluence_. Вариант для _Confluence_ выбирается на основании таблицы:

[cols="3,2,6"]
|===
|Asciidoctor |Confluence |Описание

|NOTE |info
|Выделение голубым фоном. Применяется для нейтральных полезных дополнений и примечаний.

|TIP |tip
|Выделение зелёным фоном. Можно использовать для определений, или для обозначения выполненных частей задачи.

|IMPORTANT |note
|Выделение жёлтым фоном. Используется для привлечения внимания к важной информации.

|CAUTION, WARNING |warning
|Выделение красным фоном. Самое заметное выделение, применяется для предостережений. Обозначает информацию, требующую особого внимания.
|===

== Тезаурус

Страница:: Она же _'страница Confluence'_ (по-английски _'page'_), базовая единица публикации, которой оперирует данная программа. Иногда в качестве синонима может использоваться _'статья'_, но _'страница'_ предпочтительнее, так как _'статья'_ -- это уже, скорее, про содержимое, а с точки зрения публикации важен лишь механический аспект.

Заголовок:: Или _название_ страницы. В Asciidoc-документе -- это рубрика первого уровня. В Confluence заголовок страницы не содержится в содержимом самой страницы, но обязательно выводится в верхней части страницы при просмотре. Также в Confluence заголовок в пределах пространства (_space_) должен быть уникален, по нему возможен поиск страницы при обращении через API.

== Полезные ссылки

. https://htmlcleaner.sourceforge.net/index.php[HtmlCleaner]

. https://htmlcleaner.sourceforge.net/parameters.php[HtmlCleaner: Setting Behavior]

. https://confluence.atlassian.com/confcloud/converting-pages-to-the-new-editor-993930226.html[Convert pages to the new editor]

. https://symbl.cc/
