:toc: left
:toc-title: Оглавление
= Особенности работы с Confluence

Особенности взаимодействия с Confluence через API. Неочевидные моменты в устройстве формата хранения (Storage format). Полезные ссылки или собственные объяснения, проясняющие перечисленное выше.

== ri:version-at-save

Это атрибут в идентификаторе ресурса-аттачмента, когда он используется внутри тега изображения (`ac:image`). Если этот атрибут не задан, Confluence может сам принудительно его заполнять при сохранении страницы. Это приводит к расхождению между отправленным содержимым и итоговым.

Судя по экспериментам, в этот атрибут может быть записана либо текущая версия аттачмента на момент сохранения, либо остаться прежняя версия. То есть она может только увеличиваться.

Есть предположение, что так сделано для того, чтобы обозначить факт изменения страницы в тех случаях, когда изменилась только картинка. Без этого в истории изменений не появлялась бы новая запись, и не было бы возможности выполнить сравнение версий.

=== Как этот атрибут будет работать при создании новой страницы

При создании новой страницы можно смело указывать в этом атрибуте версию `"1"`. Confluence нормально это воспринимает, даже несмотря на то, что в момент сохранения содержимого ещё нет никаких вложений.

=== Как этот атрибут будет работать при обновлении страницы

При обновлении страницы рассматриваются текущие файлы изображений, упомянутых в содержимом. Для принятия решения о загрузке новой версии изображения во вложение выполняется сравнение содержимого файла с последней версией вложения.

. Если расхождения нет, загружать новую версию вложения не требуется. В ссылке на вложение в содержимом страницы в таком случае можно указать последнюю версию вложения. С большой вероятностью она совпадёт с тем значением, которое было там до текущего обновления.

. Если файл картинки изменился относительно последней версии вложения, его нужно обновить, то есть загрузить новую версию вложения. В ссылках на это изображение нужно указать новый номер версии.

_При обновлении, в отличие от первичной публикации страницы, сначала обрабатываются вложения и только после этого выполняется обновление основного содержимого._

== Идентификаторы в макросах

Confluence использует UUID-идентификаторы в каждом макросе. Если попытаться опубликовать страницу, на которой будут макросы без идентификаторов, Confluence назначит их сам. Если верить https://community.developer.atlassian.com/t/what-is-the-purpose-of-macro-id-in-the-source-xml/18590/3[ответу с форума], эти идентификаторы должны быть уникальны в рамках одной страницы. Судя по всему, Confluence их используется для того, чтобы можно было формально различать (идентифицировать) разные экземпляры макросов на одной странице.

=== Как ConfluenceConverter назначает идентификаторы макросам

`ConfluenceConverter` создаёт идентификатор на основании какой-то части контента макроса. Это лучше, чем генерировать случайный идентификатор, так как не приводит к изменениям в содержимом страницы, если не было реальных изменений в контенте макроса.

Для случая вложенных макросов, когда на основании общего контента нужно создать два различных идентификатора, первый создаётся как описано выше, а второй создаётся _xor_-наложением на первый какого-то константного UUID, зафиксированного на этапе разработки конвертера.

== Полезные ссылки

. https://confluence.atlassian.com/conf79/confluence-storage-format-1027128771.html[Confluence Storage Format] -- описание формата хранения Confluence, впрочем, не слишком глубокое.

. https://community.developer.atlassian.com/t/what-is-the-purpose-of-macro-id-in-the-source-xml/18590/3[What is the purpose of macro-id in the source XML?]
